{
 "title": "Grafana-Kafka",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "logsDataSource", "label": "Logs Data Source", "query": "grafanacloud-ddr1-logs" }
  ]
 },
 "panels": [
  {
   "title": "GeoMap",
   "type": "geomap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (state) (count_over_time( {job=\"kafka\",topic=\"grafana\"} | json | state!=\"\" | __error__=\"\" [5m]) )",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Top Activity by State",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk( 4, sum by (state) (count_over_time( {job=\"kafka\",topic=\"grafana\"} | json | state!=\"\" | __error__=\"\" [15m]) ) )",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Job Status",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (rate( {job=\"kafka\"} | json [1h] ) * 3600 )",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Process Events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (processName) (sum_over_time( {job=\"kafka\"} | json | unwrap count [$__interval] ))",
     "legendFormat": "{{processName}}"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 7 },
   "targets": [
    {
     "expr": "sum by (statusCode) (count_over_time( {job=\"kafka\"} | json [$__interval] ))",
     "legendFormat": "{{statusCode}}"
    }
   ]
  },
  {
   "title": "Log Lines",
   "type": "logs",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{job=\"kafka\", topic=\"grafana\"} | json | line_format \"{{indent 0 .state}}\\t{{indent 0 .host}}\\t{{.status}}\\t{{.statusCode}}\"",
     "legendFormat": "{{statusCode}}"
    }
   ]
  },
  {
   "title": "Log Messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 11, "y": 12 },
   "targets": [
    {
     "expr": "sum by (job) (rate( {job=\"kafka\"} [5m] ) * 60 )",
     "legendFormat": "Messages Per Minute"
    },
    {
     "expr": "sum by (job) (bytes_rate( {job=\"kafka\"} [5m] ) * 60 )",
     "legendFormat": "Messages Bytes Per Minute"
    }
   ]
  },
  {
   "title": "Log Messages",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 17, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (rate( {job=\"kafka\"} [5m] ) * 60 )",
     "legendFormat": "Messages Per Minute"
    },
    {
     "expr": "sum by (job) (bytes_rate( {job=\"kafka\"} [5m] ) * 60 )",
     "legendFormat": "Messages Bytes Per Minute"
    },
    {
     "expr": "sum by (job) (bytes_over_time( {job=\"kafka\"} [$__range] ))",
     "legendFormat": "Total Message Bytes"
    },
    {
     "expr": "( sum by (job) (bytes_rate( {job=\"kafka\"} [5m] ) * 60 ) ) / ( sum by (job) (rate( {job=\"kafka\"} [5m] ) * 60 ) )",
     "legendFormat": "Message Size (AVG)"
    }
   ]
  }
 ]
}